export default {
  trazi: "",
  kategorije: [
    { naslov: "Romani" },
    { naslov: "Znanstvena fantastika" },
    { naslov: "Drama" },
    { naslov: "Poezija" },
    { naslov: "Knjige za djecu" },
    { naslov: "Biografija" },
    { naslov: "Povijest" },
    { naslov: "Religija" },
    { naslov: "Umjetnost" },
    { naslov: "Znanost i tehnologija" },
  ],
  optionsKategorije: [
    { value: "", text: "Kategorija", disabled: true },
    "Romani",
    "Znanstvena fantastika",
    "Drama",
    "Poezija",
    "Knjige za djecu",
    "Biografija",
    "Povijest",
    "Religija",
    "Umjetnost",
    "Znanost i tehnologija",
  ],
  optionsStanje: [
    { value: "", text: "Stanje", disabled: true },
    "Loše",
    "Dobro",
    "Kao novo",
  ],
  optionsUvez: [{ value: "", text: "Uvez", disabled: true }, "Tvrdi", "Meki"],
};
